M48
; DRILL file {KiCad (6.0.0)} date Sat Jan  1 11:54:24 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-01T11:54:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T2
X153.0Y-148.0
T1
X153.25Y-152.4G85X152.75Y-152.4
G05
T0
M30
